# Generated by Django 3.2.4 on 2021-10-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_login_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
    ]
