# Generated by Django 3.2.4 on 2021-07-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210727_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mob_email',
        ),
    ]
