# Generated by Django 3.2.4 on 2021-08-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
